[project]
name = "pytorch-test"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "matplotlib>=3.10.9",
    "prettytable>=3.17.0",
    "torch>=2.12.0",
    "torchvision>=0.27.0",
    "tqdm>=4.67.3",
]

[[tool.uv.index]]
url = "https://mirrors.ustc.edu.cn/pypi/web/simple"
default = true

[[tool.uv.index]]
name = "pytorch-cu126-mirror"
url = "https://mirrors.nju.edu.cn/pytorch/whl/cu126"
explicit = true

[[tool.uv.index]]
name = "pytorch-cu126"
url = "https://download.pytorch.org/whl/cu126"
explicit = true

[tool.uv.sources]
torch = { index = "pytorch-cu126-mirror" }
torchvision = { index = "pytorch-cu126-mirror" }
